/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Strongly typed relationship designations for directional graph edges.
 */
export enum RelationshipType {
  CONTAINS = 'CONTAINS',
  REFERENCES = 'REFERENCES',
  USES = 'USES',
  DEPENDS_ON = 'DEPENDS_ON',
  RELATED_TO = 'RELATED_TO',
  EXPLAINS = 'EXPLAINS',
  SUMMARIZES = 'SUMMARIZES',
  HAS_FORMULA = 'HAS_FORMULA',
  HAS_NOTE = 'HAS_NOTE',
  HAS_RESOURCE = 'HAS_RESOURCE',
  HAS_SESSION = 'HAS_SESSION',
  HAS_FLASHCARD = 'HAS_FLASHCARD',
  HAS_REVISION = 'HAS_REVISION',
  GENERATED_FROM = 'GENERATED_FROM',
  CONTAINS_TEXT = 'CONTAINS_TEXT',
  CONTAINS_IMAGE = 'CONTAINS_IMAGE',
  LINKED_TO_READING = 'LINKED_TO_READING',
  LINKED_TO_LOS = 'LINKED_TO_LOS',
  EXTRACTED_FORMULA = 'EXTRACTED_FORMULA',
  REFERENCED_BY_NOTE = 'REFERENCED_BY_NOTE',
  VIEWED_IN_SESSION = 'VIEWED_IN_SESSION',
  ANNOTATED_BY = 'ANNOTATED_BY'
}
